language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
os: linux
dist: trusty
sudo: required
addons:
    #apt:
    #    packages:
    #    - libopenblas-dev
    #    - liblapack-dev
    #    - liblapacke-dev
install:
    - docker pull ubuntu:xenial
    - pip install coveralls
    #- python setup.py install
script:
    - >
      docker run -e "PYTHONVERSION=$(python -c 'import platform; print(platform.python_version())')" -v $(pwd):/app ubuntu:xenial bash -c "
      apt-get update &&
      apt-get install -y wget bzip2 build-essential libopenblas-dev liblapack-dev liblapacke-dev &&
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh &&
      bash Miniconda3-latest-Linux-x86_64.sh -b &&
      /root/miniconda3/bin/conda config --set always_yes yes --set changeps1 no &&
      /root/miniconda3/bin/conda create -n testenv python=${PYTHONVERSION} &&
      source /root/miniconda3/bin/activate testenv &&
      python -V &&
      pip install nose coveralls &&
      cd app &&
      python setup.py install &&
      nosetests --with-coverage --cover-package=prox_tv
      "
after_success:
    - coveralls
